var annotated_dup =
[
    [ "Catch", "namespace_catch.html", [
      [ "Detail", "namespace_catch_1_1_detail.html", [
        [ "EnumInfo", "struct_catch_1_1_detail_1_1_enum_info.html", "struct_catch_1_1_detail_1_1_enum_info" ],
        [ "IsStreamInsertable", "class_catch_1_1_detail_1_1_is_stream_insertable.html", "class_catch_1_1_detail_1_1_is_stream_insertable" ],
        [ "Approx", "class_catch_1_1_detail_1_1_approx.html", "class_catch_1_1_detail_1_1_approx" ]
      ] ],
      [ "detail", "namespace_catch_1_1detail.html", [
        [ "void_type", "struct_catch_1_1detail_1_1void__type.html", "struct_catch_1_1detail_1_1void__type" ],
        [ "is_range_impl", "struct_catch_1_1detail_1_1is__range__impl.html", null ],
        [ "is_range_impl< T, typename void_type< decltype(begin(std::declval< T >()))>::type >", "struct_catch_1_1detail_1_1is__range__impl_3_01_t_00_01typename_01void__type_3_01decltype_07begin8604ecb9de16ea7789f2f694ac896ffd.html", null ]
      ] ],
      [ "Generators", "namespace_catch_1_1_generators.html", [
        [ "GeneratorUntypedBase", "class_catch_1_1_generators_1_1_generator_untyped_base.html", "class_catch_1_1_generators_1_1_generator_untyped_base" ],
        [ "IGenerator", "struct_catch_1_1_generators_1_1_i_generator.html", "struct_catch_1_1_generators_1_1_i_generator" ],
        [ "SingleValueGenerator", "class_catch_1_1_generators_1_1_single_value_generator.html", "class_catch_1_1_generators_1_1_single_value_generator" ],
        [ "FixedValuesGenerator", "class_catch_1_1_generators_1_1_fixed_values_generator.html", "class_catch_1_1_generators_1_1_fixed_values_generator" ],
        [ "GeneratorWrapper", "class_catch_1_1_generators_1_1_generator_wrapper.html", "class_catch_1_1_generators_1_1_generator_wrapper" ],
        [ "Generators", "class_catch_1_1_generators_1_1_generators.html", "class_catch_1_1_generators_1_1_generators" ],
        [ "as", "struct_catch_1_1_generators_1_1as.html", null ],
        [ "TakeGenerator", "class_catch_1_1_generators_1_1_take_generator.html", "class_catch_1_1_generators_1_1_take_generator" ],
        [ "FilterGenerator", "class_catch_1_1_generators_1_1_filter_generator.html", "class_catch_1_1_generators_1_1_filter_generator" ],
        [ "RepeatGenerator", "class_catch_1_1_generators_1_1_repeat_generator.html", "class_catch_1_1_generators_1_1_repeat_generator" ],
        [ "MapGenerator", "class_catch_1_1_generators_1_1_map_generator.html", "class_catch_1_1_generators_1_1_map_generator" ],
        [ "ChunkGenerator", "class_catch_1_1_generators_1_1_chunk_generator.html", "class_catch_1_1_generators_1_1_chunk_generator" ],
        [ "RandomFloatingGenerator", "class_catch_1_1_generators_1_1_random_floating_generator.html", "class_catch_1_1_generators_1_1_random_floating_generator" ],
        [ "RandomIntegerGenerator", "class_catch_1_1_generators_1_1_random_integer_generator.html", "class_catch_1_1_generators_1_1_random_integer_generator" ],
        [ "RangeGenerator", "class_catch_1_1_generators_1_1_range_generator.html", "class_catch_1_1_generators_1_1_range_generator" ],
        [ "IteratorGenerator", "class_catch_1_1_generators_1_1_iterator_generator.html", "class_catch_1_1_generators_1_1_iterator_generator" ]
      ] ],
      [ "Matchers", "namespace_catch_1_1_matchers.html", [
        [ "Exception", "namespace_catch_1_1_matchers_1_1_exception.html", [
          [ "ExceptionMessageMatcher", "class_catch_1_1_matchers_1_1_exception_1_1_exception_message_matcher.html", "class_catch_1_1_matchers_1_1_exception_1_1_exception_message_matcher" ]
        ] ],
        [ "Floating", "namespace_catch_1_1_matchers_1_1_floating.html", [
          [ "WithinAbsMatcher", "struct_catch_1_1_matchers_1_1_floating_1_1_within_abs_matcher.html", "struct_catch_1_1_matchers_1_1_floating_1_1_within_abs_matcher" ],
          [ "WithinUlpsMatcher", "struct_catch_1_1_matchers_1_1_floating_1_1_within_ulps_matcher.html", "struct_catch_1_1_matchers_1_1_floating_1_1_within_ulps_matcher" ],
          [ "WithinRelMatcher", "struct_catch_1_1_matchers_1_1_floating_1_1_within_rel_matcher.html", "struct_catch_1_1_matchers_1_1_floating_1_1_within_rel_matcher" ]
        ] ],
        [ "Generic", "namespace_catch_1_1_matchers_1_1_generic.html", [
          [ "PredicateMatcher", "class_catch_1_1_matchers_1_1_generic_1_1_predicate_matcher.html", "class_catch_1_1_matchers_1_1_generic_1_1_predicate_matcher" ]
        ] ],
        [ "Impl", "namespace_catch_1_1_matchers_1_1_impl.html", [
          [ "MatchAllOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_all_of.html", "struct_catch_1_1_matchers_1_1_impl_1_1_match_all_of" ],
          [ "MatchAnyOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_any_of.html", "struct_catch_1_1_matchers_1_1_impl_1_1_match_any_of" ],
          [ "MatchNotOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_not_of.html", "struct_catch_1_1_matchers_1_1_impl_1_1_match_not_of" ],
          [ "MatcherUntypedBase", "class_catch_1_1_matchers_1_1_impl_1_1_matcher_untyped_base.html", "class_catch_1_1_matchers_1_1_impl_1_1_matcher_untyped_base" ],
          [ "MatcherMethod", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_method.html", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_method" ],
          [ "MatcherBase", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_base.html", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_base" ]
        ] ],
        [ "StdString", "namespace_catch_1_1_matchers_1_1_std_string.html", [
          [ "CasedString", "struct_catch_1_1_matchers_1_1_std_string_1_1_cased_string.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_cased_string" ],
          [ "StringMatcherBase", "struct_catch_1_1_matchers_1_1_std_string_1_1_string_matcher_base.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_string_matcher_base" ],
          [ "EqualsMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_equals_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_equals_matcher" ],
          [ "ContainsMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_contains_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_contains_matcher" ],
          [ "StartsWithMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_starts_with_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_starts_with_matcher" ],
          [ "EndsWithMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_ends_with_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_ends_with_matcher" ],
          [ "RegexMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_regex_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_regex_matcher" ]
        ] ],
        [ "Vector", "namespace_catch_1_1_matchers_1_1_vector.html", [
          [ "ContainsElementMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_element_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_element_matcher" ],
          [ "ContainsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_matcher" ],
          [ "EqualsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_equals_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_equals_matcher" ],
          [ "ApproxMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_approx_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_approx_matcher" ],
          [ "UnorderedEqualsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_unordered_equals_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_unordered_equals_matcher" ]
        ] ]
      ] ],
      [ "CaseSensitive", "struct_catch_1_1_case_sensitive.html", "struct_catch_1_1_case_sensitive" ],
      [ "NonCopyable", "class_catch_1_1_non_copyable.html", "class_catch_1_1_non_copyable" ],
      [ "SourceLineInfo", "struct_catch_1_1_source_line_info.html", "struct_catch_1_1_source_line_info" ],
      [ "StreamEndStop", "struct_catch_1_1_stream_end_stop.html", "struct_catch_1_1_stream_end_stop" ],
      [ "RegistrarForTagAliases", "struct_catch_1_1_registrar_for_tag_aliases.html", "struct_catch_1_1_registrar_for_tag_aliases" ],
      [ "ITestInvoker", "struct_catch_1_1_i_test_invoker.html", "struct_catch_1_1_i_test_invoker" ],
      [ "ITestCaseRegistry", "struct_catch_1_1_i_test_case_registry.html", "struct_catch_1_1_i_test_case_registry" ],
      [ "StringRef", "class_catch_1_1_string_ref.html", "class_catch_1_1_string_ref" ],
      [ "always_false", "struct_catch_1_1always__false.html", null ],
      [ "true_given", "struct_catch_1_1true__given.html", null ],
      [ "is_callable_tester", "struct_catch_1_1is__callable__tester.html", "struct_catch_1_1is__callable__tester" ],
      [ "is_callable", "struct_catch_1_1is__callable.html", null ],
      [ "is_callable< Fun(Args...)>", "struct_catch_1_1is__callable_3_01_fun_07_args_8_8_8_08_4.html", null ],
      [ "TestInvokerAsMethod", "class_catch_1_1_test_invoker_as_method.html", "class_catch_1_1_test_invoker_as_method" ],
      [ "NameAndTags", "struct_catch_1_1_name_and_tags.html", "struct_catch_1_1_name_and_tags" ],
      [ "AutoReg", "struct_catch_1_1_auto_reg.html", "struct_catch_1_1_auto_reg" ],
      [ "ResultWas", "struct_catch_1_1_result_was.html", "struct_catch_1_1_result_was" ],
      [ "ResultDisposition", "struct_catch_1_1_result_disposition.html", "struct_catch_1_1_result_disposition" ],
      [ "AssertionInfo", "struct_catch_1_1_assertion_info.html", "struct_catch_1_1_assertion_info" ],
      [ "IStream", "struct_catch_1_1_i_stream.html", "struct_catch_1_1_i_stream" ],
      [ "ReusableStringStream", "class_catch_1_1_reusable_string_stream.html", "class_catch_1_1_reusable_string_stream" ],
      [ "IMutableEnumValuesRegistry", "struct_catch_1_1_i_mutable_enum_values_registry.html", "struct_catch_1_1_i_mutable_enum_values_registry" ],
      [ "StringMaker", "struct_catch_1_1_string_maker.html", "struct_catch_1_1_string_maker" ],
      [ "StringMaker< std::string >", "struct_catch_1_1_string_maker_3_01std_1_1string_01_4.html", "struct_catch_1_1_string_maker_3_01std_1_1string_01_4" ],
      [ "StringMaker< char const * >", "struct_catch_1_1_string_maker_3_01char_01const_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01char_01const_01_5_01_4" ],
      [ "StringMaker< char * >", "struct_catch_1_1_string_maker_3_01char_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01char_01_5_01_4" ],
      [ "StringMaker< std::wstring >", "struct_catch_1_1_string_maker_3_01std_1_1wstring_01_4.html", "struct_catch_1_1_string_maker_3_01std_1_1wstring_01_4" ],
      [ "StringMaker< wchar_t const * >", "struct_catch_1_1_string_maker_3_01wchar__t_01const_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01wchar__t_01const_01_5_01_4" ],
      [ "StringMaker< wchar_t * >", "struct_catch_1_1_string_maker_3_01wchar__t_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01wchar__t_01_5_01_4" ],
      [ "StringMaker< char[SZ]>", "struct_catch_1_1_string_maker_3_01char_0f_s_z_0e_4.html", "struct_catch_1_1_string_maker_3_01char_0f_s_z_0e_4" ],
      [ "StringMaker< signed char[SZ]>", "struct_catch_1_1_string_maker_3_01signed_01char_0f_s_z_0e_4.html", "struct_catch_1_1_string_maker_3_01signed_01char_0f_s_z_0e_4" ],
      [ "StringMaker< unsigned char[SZ]>", "struct_catch_1_1_string_maker_3_01unsigned_01char_0f_s_z_0e_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01char_0f_s_z_0e_4" ],
      [ "StringMaker< int >", "struct_catch_1_1_string_maker_3_01int_01_4.html", "struct_catch_1_1_string_maker_3_01int_01_4" ],
      [ "StringMaker< long >", "struct_catch_1_1_string_maker_3_01long_01_4.html", "struct_catch_1_1_string_maker_3_01long_01_4" ],
      [ "StringMaker< long long >", "struct_catch_1_1_string_maker_3_01long_01long_01_4.html", "struct_catch_1_1_string_maker_3_01long_01long_01_4" ],
      [ "StringMaker< unsigned int >", "struct_catch_1_1_string_maker_3_01unsigned_01int_01_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01int_01_4" ],
      [ "StringMaker< unsigned long >", "struct_catch_1_1_string_maker_3_01unsigned_01long_01_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01long_01_4" ],
      [ "StringMaker< unsigned long long >", "struct_catch_1_1_string_maker_3_01unsigned_01long_01long_01_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01long_01long_01_4" ],
      [ "StringMaker< bool >", "struct_catch_1_1_string_maker_3_01bool_01_4.html", "struct_catch_1_1_string_maker_3_01bool_01_4" ],
      [ "StringMaker< char >", "struct_catch_1_1_string_maker_3_01char_01_4.html", "struct_catch_1_1_string_maker_3_01char_01_4" ],
      [ "StringMaker< signed char >", "struct_catch_1_1_string_maker_3_01signed_01char_01_4.html", "struct_catch_1_1_string_maker_3_01signed_01char_01_4" ],
      [ "StringMaker< unsigned char >", "struct_catch_1_1_string_maker_3_01unsigned_01char_01_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01char_01_4" ],
      [ "StringMaker< std::nullptr_t >", "struct_catch_1_1_string_maker_3_01std_1_1nullptr__t_01_4.html", "struct_catch_1_1_string_maker_3_01std_1_1nullptr__t_01_4" ],
      [ "StringMaker< float >", "struct_catch_1_1_string_maker_3_01float_01_4.html", "struct_catch_1_1_string_maker_3_01float_01_4" ],
      [ "StringMaker< double >", "struct_catch_1_1_string_maker_3_01double_01_4.html", "struct_catch_1_1_string_maker_3_01double_01_4" ],
      [ "StringMaker< T * >", "struct_catch_1_1_string_maker_3_01_t_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01_t_01_5_01_4" ],
      [ "StringMaker< R C::* >", "struct_catch_1_1_string_maker_3_01_r_01_c_1_1_5_01_4.html", "struct_catch_1_1_string_maker_3_01_r_01_c_1_1_5_01_4" ],
      [ "is_range", "struct_catch_1_1is__range.html", null ],
      [ "StringMaker< R, typename std::enable_if< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable< R >::value >::type >", "struct_catch_1_1_string_maker_3_01_r_00_01typename_01std_1_1enable__if_3_01is__range_3_01_r_01_4536d8fedfff6d62432b3dc59b56e1380.html", "struct_catch_1_1_string_maker_3_01_r_00_01typename_01std_1_1enable__if_3_01is__range_3_01_r_01_4536d8fedfff6d62432b3dc59b56e1380" ],
      [ "StringMaker< T[SZ]>", "struct_catch_1_1_string_maker_3_01_t_0f_s_z_0e_4.html", "struct_catch_1_1_string_maker_3_01_t_0f_s_z_0e_4" ],
      [ "ITransientExpression", "struct_catch_1_1_i_transient_expression.html", "struct_catch_1_1_i_transient_expression" ],
      [ "BinaryExpr", "class_catch_1_1_binary_expr.html", "class_catch_1_1_binary_expr" ],
      [ "UnaryExpr", "class_catch_1_1_unary_expr.html", "class_catch_1_1_unary_expr" ],
      [ "ExprLhs", "class_catch_1_1_expr_lhs.html", "class_catch_1_1_expr_lhs" ],
      [ "Decomposer", "struct_catch_1_1_decomposer.html", "struct_catch_1_1_decomposer" ],
      [ "IResultCapture", "struct_catch_1_1_i_result_capture.html", "struct_catch_1_1_i_result_capture" ],
      [ "TestFailureException", "struct_catch_1_1_test_failure_exception.html", null ],
      [ "LazyExpression", "class_catch_1_1_lazy_expression.html", "class_catch_1_1_lazy_expression" ],
      [ "AssertionReaction", "struct_catch_1_1_assertion_reaction.html", "struct_catch_1_1_assertion_reaction" ],
      [ "AssertionHandler", "class_catch_1_1_assertion_handler.html", "class_catch_1_1_assertion_handler" ],
      [ "MessageInfo", "struct_catch_1_1_message_info.html", "struct_catch_1_1_message_info" ],
      [ "MessageStream", "struct_catch_1_1_message_stream.html", "struct_catch_1_1_message_stream" ],
      [ "MessageBuilder", "struct_catch_1_1_message_builder.html", "struct_catch_1_1_message_builder" ],
      [ "ScopedMessage", "class_catch_1_1_scoped_message.html", "class_catch_1_1_scoped_message" ],
      [ "Capturer", "class_catch_1_1_capturer.html", "class_catch_1_1_capturer" ],
      [ "Counts", "struct_catch_1_1_counts.html", "struct_catch_1_1_counts" ],
      [ "Totals", "struct_catch_1_1_totals.html", "struct_catch_1_1_totals" ],
      [ "SectionInfo", "struct_catch_1_1_section_info.html", "struct_catch_1_1_section_info" ],
      [ "SectionEndInfo", "struct_catch_1_1_section_end_info.html", "struct_catch_1_1_section_end_info" ],
      [ "Timer", "class_catch_1_1_timer.html", "class_catch_1_1_timer" ],
      [ "Section", "class_catch_1_1_section.html", "class_catch_1_1_section" ],
      [ "IRegistryHub", "struct_catch_1_1_i_registry_hub.html", "struct_catch_1_1_i_registry_hub" ],
      [ "IMutableRegistryHub", "struct_catch_1_1_i_mutable_registry_hub.html", "struct_catch_1_1_i_mutable_registry_hub" ],
      [ "IExceptionTranslator", "struct_catch_1_1_i_exception_translator.html", "struct_catch_1_1_i_exception_translator" ],
      [ "IExceptionTranslatorRegistry", "struct_catch_1_1_i_exception_translator_registry.html", "struct_catch_1_1_i_exception_translator_registry" ],
      [ "ExceptionTranslatorRegistrar", "class_catch_1_1_exception_translator_registrar.html", "class_catch_1_1_exception_translator_registrar" ],
      [ "StringMaker< Catch::Detail::Approx >", "struct_catch_1_1_string_maker_3_01_catch_1_1_detail_1_1_approx_01_4.html", "struct_catch_1_1_string_maker_3_01_catch_1_1_detail_1_1_approx_01_4" ],
      [ "pluralise", "struct_catch_1_1pluralise.html", "struct_catch_1_1pluralise" ],
      [ "MatchExpr", "class_catch_1_1_match_expr.html", "class_catch_1_1_match_expr" ],
      [ "IGeneratorTracker", "struct_catch_1_1_i_generator_tracker.html", "struct_catch_1_1_i_generator_tracker" ],
      [ "GeneratorException", "class_catch_1_1_generator_exception.html", "class_catch_1_1_generator_exception" ],
      [ "IContext", "struct_catch_1_1_i_context.html", "struct_catch_1_1_i_context" ],
      [ "IMutableContext", "struct_catch_1_1_i_mutable_context.html", "struct_catch_1_1_i_mutable_context" ],
      [ "Option", "class_catch_1_1_option.html", "class_catch_1_1_option" ],
      [ "WarnAbout", "struct_catch_1_1_warn_about.html", "struct_catch_1_1_warn_about" ],
      [ "ShowDurations", "struct_catch_1_1_show_durations.html", "struct_catch_1_1_show_durations" ],
      [ "RunTests", "struct_catch_1_1_run_tests.html", "struct_catch_1_1_run_tests" ],
      [ "UseColour", "struct_catch_1_1_use_colour.html", "struct_catch_1_1_use_colour" ],
      [ "WaitForKeypress", "struct_catch_1_1_wait_for_keypress.html", "struct_catch_1_1_wait_for_keypress" ],
      [ "IConfig", "struct_catch_1_1_i_config.html", "struct_catch_1_1_i_config" ],
      [ "SimplePcg32", "class_catch_1_1_simple_pcg32.html", "class_catch_1_1_simple_pcg32" ],
      [ "TestCaseInfo", "struct_catch_1_1_test_case_info.html", "struct_catch_1_1_test_case_info" ],
      [ "TestCase", "class_catch_1_1_test_case.html", "class_catch_1_1_test_case" ],
      [ "IRunner", "struct_catch_1_1_i_runner.html", "struct_catch_1_1_i_runner" ]
    ] ],
    [ "Bonus", "class_bonus.html", "class_bonus" ],
    [ "Burger", "class_burger.html", "class_burger" ],
    [ "Catch_global_namespace_dummy", "struct_catch__global__namespace__dummy.html", null ],
    [ "Egg", "class_egg.html", "class_egg" ],
    [ "Enemy", "class_enemy.html", "class_enemy" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "Level", "class_level.html", "class_level" ],
    [ "Movable", "class_movable.html", "class_movable" ],
    [ "Pepper", "class_pepper.html", "class_pepper" ],
    [ "Pickle", "class_pickle.html", "class_pickle" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "Sausage", "class_sausage.html", "class_sausage" ],
    [ "Score", "class_score.html", "class_score" ],
    [ "Sheet", "class_sheet.html", "class_sheet" ],
    [ "Slice", "class_slice.html", "class_slice" ],
    [ "SpriteSheet", "class_sprite_sheet.html", "class_sprite_sheet" ],
    [ "Updatable", "class_updatable.html", "class_updatable" ]
];